### ISSUE TITLE
Add support for MoE model architecture

### ISSUE THREAD

**Issue by gnadathur** [pytorch/torchtitan#184]
```[tasklist]
### Tasks
- [ ] Add barebone MoE without expert parallelism
- [ ] Prototype expert parallel with MoE
- [ ] e2e integration and perf validation with torchtrain
```

**Comment by aonrdbit** [comment]
Great! is there any update to this feature?

**Comment by tianyu-l** [comment]
This is under planning and will be worked on soon. Any suggestions are welcome.
