### ISSUE TITLE
benchmarking perf numbers and loss convergence

### ISSUE THREAD

**Issue by tianyu-l** [pytorch/torchtitan#394]
```[tasklist]
### Tasks
- [x] discuss what to add / show in https://github.com/pytorch/torchtitan/blob/main/docs/performance.md
- [x] (ETA 10/31) rerun 1D + torch.compile on 8B 128 GPU https://github.com/pytorch/torchtitan/issues/619
- [x] float8 perf regression investigation
- [x] loss convergence runs
- [x] 3D 405B with Zero-Bubble PP (might need to revisit)
```

**Comment by casper-hansen** [comment]
@tianyu-l It would be good if you can also add the bandwidth that you had available per GPU in the cluster. I tried recreating the MFU numbers, only to realize that the A100 cluster only brought 200 GB/s bandwidth where as your AWS cluster brings 400 GB/s with EFA, creating a significant difference between the MFU achievable.
