### ISSUE TITLE
add Llama 3.2 support

### ISSUE THREAD

**Issue by tianyu-l** [pytorch/torchtitan#625]
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/torchtitan/pull/589
- [ ] https://github.com/pytorch/torchtitan/pull/626
- [ ] Numerically stable validation for ViT
- [ ] Numerically stable validation for decoder
- [ ] Enable dataloading for dataset OBELICS and update the tokenizer
- [ ] enabling loading the pretrained checkpoints for ViT and non-crossed layer in decoder
- [ ] Training receipe for MM model
- [ ] Perf and numerically stability for 1D (FSDP) for MM model
```

**Comment by TJ-Solergibert** [comment]
Hi @tianyu-l, is anyone working on the `Enable dataloading for dataset OBELICS and update the tokenizer` task? Let me know if I could contribute to this task!

**Comment by tianyu-l** [comment]
Hi @TJ-Solergibert, it'd be great if you can help on that. I can help discuss and review the code / design / etc. You may create a separate issue (and add the link above) to track progress if needed.

**Comment by fduwjj** [comment]
@TJ-Solergibert you can add me as the code reviewer as well.
