### ISSUE TITLE
[rfc] torchtitan release practices

### ISSUE THREAD

**Issue by tianyu-l** [pytorch/torchtitan#688]
```[tasklist]
### Tasks
- [ ] update the version number in version.txt (following https://semver.org/)
- [ ] create a corresponding "lightweight" tag using e.g. `git tag v1.0.0` locally ([instruction](https://git-scm.com/book/en/v2/Git-Basics-Tagging)) and push to github
- [ ] update github repo release ([instruction](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)) with release notes, including proper nightly dependencies (e.g. for torch and torchao)
- [ ] update the torchtitan package on pypi
```
